language: node_js
node_js:
  - 12
scripts:
  - npm run build

deploy: 
  - provider: npm
    email: severecloud@gmail.com
    api_key: $NPM_TOKEN
    skip_cleanup: true
    on:
      tags: true
  - provider: pages
    local-dir: public
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
      branch: master
